CREATE DATABASE DB_Teste;

CREATE TABLE TB_Perfil (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NomePerfil VARCHAR(100) NOT NULL,
);

CREATE TABLE TB_Usuarios (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	PerfilId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES TB_Perfil (Id),
	Nome VARCHAR(100) NOT NULL,
	Telefone VARCHAR(14) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Sexo VARCHAR(20) NOT NULL,
	Endereco VARCHAR(100) NOT NULL,
	Cidade VARCHAR(20) NOT NULL,
	Estado VARCHAR(20) NOT NULL,
	Ativo BIT DEFAULT 0,
);